/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import AUXILIAR.AuxiliarLog;
import OperacaoBanco.OperacaoBancoMovimento;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import jxl.read.biff.BiffException;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author André Felipe
 */
public class TelaParamMovProdData extends javax.swing.JFrame {

    JLabel transferirdados;

    public TelaParamMovProdData() {
        initComponents();
    }

    public TelaParamMovProdData(JLabel transferirdados) {
        initComponents();
        this.transferirdados = transferirdados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jtfDe = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfAte = new javax.swing.JFormattedTextField();
        jbFiltrar = new javax.swing.JButton();
        jtfCodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtro");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel9.setText("Cod");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 10, 30, 30);

        jtfDe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jtfDe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jtfDe);
        jtfDe.setBounds(260, 40, 120, 20);

        jLabel10.setText("Até:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(230, 70, 30, 30);

        jtfAte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jtfAte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jtfAte);
        jtfAte.setBounds(260, 70, 120, 20);

        jbFiltrar.setText("Filtrar");
        jbFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbFiltrar);
        jbFiltrar.setBounds(230, 100, 150, 30);

        jtfCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jtfCodigo);
        jtfCodigo.setBounds(260, 10, 120, 20);

        jLabel11.setText("De:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(230, 40, 40, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/tela carregando.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 420, 180);

        setSize(new java.awt.Dimension(414, 179));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFiltrarActionPerformed

        try {

            HashMap parametro = new HashMap<>();
            parametro.put("dtInicio", new SimpleDateFormat("dd/MM/yyyy").parse(jtfDe.getText()));
            parametro.put("dtFim", new SimpleDateFormat("dd/MM/yyyy").parse(jtfAte.getText()));
            parametro.put("codProd", Integer.parseInt(jtfCodigo.getText()));

            OperacaoBanco.OperacaoBancoMovimento ob = null;
            ob = new OperacaoBancoMovimento();
            ob.obterConexao();

            String src = "Jasper/movimentoPorProdData.jasper";
            JasperPrint jasperPrint = null;
            jasperPrint = JasperFillManager.fillReport(src, parametro, ob.obterConexao());
            JasperViewer view = new JasperViewer(jasperPrint, false);
            view.setVisible(true);
            
            ob.fechaConexao();
            dispose();

            AUXILIAR.AuxiliarLog log = new AuxiliarLog();
            log.log(transferirdados.getText(), "MOVIMENTO", "RELATÓRIO", Long.parseLong("612"));

        } catch (IOException ex) {
            Logger.getLogger(TelaMovimento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaMovimento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            System.out.println("ERRO: " + ex.getMessage());
        } catch (ParseException ex) {
            Logger.getLogger(TelaMovimento.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbFiltrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaParamMovProdData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaParamMovProdData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaParamMovProdData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaParamMovProdData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaParamMovProdData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbFiltrar;
    private javax.swing.JFormattedTextField jtfAte;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JFormattedTextField jtfDe;
    // End of variables declaration//GEN-END:variables
}
