/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import AUXILIAR.AuxiliarControleAcesso;
import AUXILIAR.AuxiliarLog;
import MODEL.ModelUsuarios;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import jxl.read.biff.BiffException;

/**
 *
 * @author André Felipe
 */
public class TelaPrincipal extends javax.swing.JFrame {

    final static int USUARIOS = 1;
    final static int CFOP = 2;
    final static int PRODUTOS = 3;
    final static int CLIENTES = 4;
    final static int XML = 5;
    final static int MOVIMENTO = 6;
    final static int CONTAGENS = 7;
    final static int AUDITORIA = 8;

    JTextField transferedados;
    int codusu;

    public TelaPrincipal() {
        ModelUsuarios usuarios = new ModelUsuarios();
        initComponents();
        jlUsuarioConectado.setText(usuarios.getLogin());
        
    }

    public TelaPrincipal(JTextField transferedados) {
        this.transferedados = transferedados;
        
    }

    public TelaPrincipal(int codusu) {
        ModelUsuarios usuarios = new ModelUsuarios();
        initComponents();
        jlUsuarioConectado.setText(usuarios.getLogin());
        this.codusu = codusu;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/IMAGENS/TELA PRINCIPAL 2.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){

                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jlBotaoUsuario = new javax.swing.JLabel();
        jlBotaoClientes = new javax.swing.JLabel();
        jlBotaoProtudos = new javax.swing.JLabel();
        jlBotaoCfop = new javax.swing.JLabel();
        jlBotaoXml = new javax.swing.JLabel();
        jlBotaoLogout = new javax.swing.JLabel();
        jlBotaoMovimento = new javax.swing.JLabel();
        jlUsuarioConectado1 = new javax.swing.JLabel();
        jlUsuarioConectado = new javax.swing.JLabel();
        jlBotaoContagens = new javax.swing.JLabel();
        jlBotaoLog = new javax.swing.JLabel();
        jlUsuarioConectado2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmUsuario = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu - Movimento XML - Versão 1.0");

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setForeground(new java.awt.Color(153, 0, 0));
        jDesktopPane1.setOpaque(false);

        jlBotaoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão usuarios.png"))); // NOI18N
        jlBotaoUsuario.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão clientes II.png"))); // NOI18N
        jlBotaoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBotaoUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBotaoUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBotaoUsuarioMouseExited(evt);
            }
        });

        jlBotaoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão clientes.png"))); // NOI18N
        jlBotaoClientes.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão clientes II.png"))); // NOI18N
        jlBotaoClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBotaoClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBotaoClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBotaoClientesMouseExited(evt);
            }
        });

        jlBotaoProtudos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão produtos.png"))); // NOI18N
        jlBotaoProtudos.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão clientes II.png"))); // NOI18N
        jlBotaoProtudos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBotaoProtudosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBotaoProtudosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBotaoProtudosMouseExited(evt);
            }
        });

        jlBotaoCfop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão cfop.png"))); // NOI18N
        jlBotaoCfop.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão clientes II.png"))); // NOI18N
        jlBotaoCfop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBotaoCfopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBotaoCfopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBotaoCfopMouseExited(evt);
            }
        });

        jlBotaoXml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão xml.png"))); // NOI18N
        jlBotaoXml.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão clientes II.png"))); // NOI18N
        jlBotaoXml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBotaoXmlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBotaoXmlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBotaoXmlMouseExited(evt);
            }
        });

        jlBotaoLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão logout.png"))); // NOI18N
        jlBotaoLogout.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão clientes II.png"))); // NOI18N
        jlBotaoLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBotaoLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBotaoLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBotaoLogoutMouseExited(evt);
            }
        });

        jlBotaoMovimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão movimento.png"))); // NOI18N
        jlBotaoMovimento.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão clientes II.png"))); // NOI18N
        jlBotaoMovimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBotaoMovimentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBotaoMovimentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBotaoMovimentoMouseExited(evt);
            }
        });

        jlUsuarioConectado1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlUsuarioConectado1.setForeground(new java.awt.Color(0, 153, 0));
        jlUsuarioConectado1.setText("Usuário conectado:");

        jlUsuarioConectado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlUsuarioConectado.setText("Usuário");

        jlBotaoContagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão contagens.png"))); // NOI18N
        jlBotaoContagens.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão clientes II.png"))); // NOI18N
        jlBotaoContagens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBotaoContagensMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBotaoContagensMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBotaoContagensMouseExited(evt);
            }
        });

        jlBotaoLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão log.png"))); // NOI18N
        jlBotaoLog.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/botão clientes II.png"))); // NOI18N
        jlBotaoLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBotaoLogMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlBotaoLogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlBotaoLogMouseExited(evt);
            }
        });

        jlUsuarioConectado2.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlUsuarioConectado2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlUsuarioConectado2.setText("F1: Usuários | F2: CFOP | F3: Produtos | F4: Clientes | F5: XML | F6: Movimento | F7: Contagens | F8: Auditoria | F12: Logout | ESC: Sair");

        jDesktopPane1.setLayer(jlBotaoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jlBotaoClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jlBotaoProtudos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jlBotaoCfop, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jlBotaoXml, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jlBotaoLogout, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jlBotaoMovimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jlUsuarioConectado1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jlUsuarioConectado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jlBotaoContagens, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jlBotaoLog, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jlUsuarioConectado2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBotaoContagens, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlBotaoMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlBotaoXml, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlBotaoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlBotaoProtudos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(704, 1027, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBotaoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlBotaoCfop, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBotaoLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlBotaoLog))
                        .addGap(21, 21, 21))))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUsuarioConectado2, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jlUsuarioConectado1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlUsuarioConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUsuarioConectado1)
                    .addComponent(jlUsuarioConectado))
                .addGap(14, 14, 14)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jlBotaoMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlBotaoContagens, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jlBotaoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jlBotaoCfop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jlBotaoLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlBotaoLog)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlBotaoProtudos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlBotaoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlBotaoXml, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jlUsuarioConectado2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Módulos");

        jmUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jmUsuario.setText("Usuários");
        jmUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jmUsuario);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem2.setText("CFOP");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem3.setText("Produtos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem4.setText("Clientes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem5.setText("XML");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem6.setText("Movimento");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem7.setText("Contagens");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem8.setText("Auditoria");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opções");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem9.setText("Sair");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(1293, 684));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlBotaoClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoClientesMouseEntered
        jlBotaoClientes.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão clientes II.png"));
    }//GEN-LAST:event_jlBotaoClientesMouseEntered

    private void jlBotaoClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoClientesMouseExited
        jlBotaoClientes.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão clientes.png"));
    }//GEN-LAST:event_jlBotaoClientesMouseExited

    private void jlBotaoClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoClientesMouseClicked
        clientes();
        
    }//GEN-LAST:event_jlBotaoClientesMouseClicked

    private void jlBotaoProtudosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoProtudosMouseEntered
        jlBotaoProtudos.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão produtos II.png"));
    }//GEN-LAST:event_jlBotaoProtudosMouseEntered

    private void jlBotaoProtudosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoProtudosMouseExited
        jlBotaoProtudos.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão produtos.png"));
    }//GEN-LAST:event_jlBotaoProtudosMouseExited

    private void jlBotaoCfopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoCfopMouseEntered
        jlBotaoCfop.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão cfop II.png"));
    }//GEN-LAST:event_jlBotaoCfopMouseEntered

    private void jlBotaoCfopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoCfopMouseExited
        jlBotaoCfop.setIcon(new ImageIcon("C:\\\\Anve\\\\Icons\\\\botão cfop.png"));
    }//GEN-LAST:event_jlBotaoCfopMouseExited

    private void jlBotaoXmlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoXmlMouseEntered
        jlBotaoXml.setIcon(new ImageIcon("C:\\\\Anve\\\\Icons\\\\botão xml II.png"));
    }//GEN-LAST:event_jlBotaoXmlMouseEntered

    private void jlBotaoXmlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoXmlMouseExited
        jlBotaoXml.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão xml.png"));
    }//GEN-LAST:event_jlBotaoXmlMouseExited

    private void jlBotaoMovimentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoMovimentoMouseEntered
        jlBotaoMovimento.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão movimento II.png"));
    }//GEN-LAST:event_jlBotaoMovimentoMouseEntered

    private void jlBotaoMovimentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoMovimentoMouseExited
        jlBotaoMovimento.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão movimento.png"));
    }//GEN-LAST:event_jlBotaoMovimentoMouseExited

    private void jlBotaoProtudosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoProtudosMouseClicked
        produtos();
        
        

    }//GEN-LAST:event_jlBotaoProtudosMouseClicked

    private void jlBotaoCfopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoCfopMouseClicked
        cfop();
        
        
    }//GEN-LAST:event_jlBotaoCfopMouseClicked

    private void jlBotaoXmlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoXmlMouseClicked
        xml();
        

    }//GEN-LAST:event_jlBotaoXmlMouseClicked

    private void jlBotaoMovimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoMovimentoMouseClicked
        movimento();
        
    }//GEN-LAST:event_jlBotaoMovimentoMouseClicked

    private void jlBotaoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoUsuarioMouseClicked
        usuarios();
        

    }//GEN-LAST:event_jlBotaoUsuarioMouseClicked

    private void jlBotaoUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoUsuarioMouseEntered
        jlBotaoUsuario.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão usuarios II.png"));
    }//GEN-LAST:event_jlBotaoUsuarioMouseEntered

    private void jlBotaoUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoUsuarioMouseExited
        jlBotaoUsuario.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão usuarios.png"));
    }//GEN-LAST:event_jlBotaoUsuarioMouseExited

    private void jlBotaoLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoLogoutMouseClicked
        logout();
    }//GEN-LAST:event_jlBotaoLogoutMouseClicked

    public void logout(){
        jlBotaoLogout.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão logout II.png"));

        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
    }
    
    private void jlBotaoLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoLogoutMouseEntered
        jlBotaoLogout.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão logout II.png"));

    }//GEN-LAST:event_jlBotaoLogoutMouseEntered

    private void jlBotaoLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoLogoutMouseExited
        jlBotaoLogout.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão logout.png"));

    }//GEN-LAST:event_jlBotaoLogoutMouseExited

    private void jlBotaoLogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoLogMouseEntered
        jlBotaoLog.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão log II.png"));
    }//GEN-LAST:event_jlBotaoLogMouseEntered

    private void jlBotaoLogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoLogMouseExited
        jlBotaoLog.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão log.png"));
    }//GEN-LAST:event_jlBotaoLogMouseExited

    private void jlBotaoLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoLogMouseClicked
        auditoria();
        

    }//GEN-LAST:event_jlBotaoLogMouseClicked

    public void usuarios() {
        jlBotaoUsuario.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão usuarios II.png"));
        TelaUsuarios tela = null;
        try {
            AUXILIAR.AuxiliarControleAcesso aux = new AuxiliarControleAcesso();
            tela = new TelaUsuarios(this.jlUsuarioConectado, this.codusu);
            if (jlUsuarioConectado.getText().equals("ADM")) {
                tela.setVisible(true);
            } else if (aux.controle(this.codusu, USUARIOS) == true) {
                tela.setVisible(true);
            }
            
            jlBotaoUsuario.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão usuarios.png"));

        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cfop(){
        TelaCfop tela = null;
        try {
            tela = new TelaCfop(this.jlUsuarioConectado, this.codusu);
            AUXILIAR.AuxiliarControleAcesso aux = new AuxiliarControleAcesso();
            if (jlUsuarioConectado.getText().equals("ADM")) {
                tela.setVisible(true);
            } else if (aux.controle(this.codusu, CFOP) == true) {
                tela.setVisible(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void produtos(){
        jlBotaoProtudos.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão produtos II.png"));
        TelaProdutos tela = null;
        try {
            tela = new TelaProdutos(jlUsuarioConectado, this.codusu);
            AUXILIAR.AuxiliarControleAcesso aux = new AuxiliarControleAcesso();
            if (jlUsuarioConectado.getText().equals("ADM")) {
                tela.setVisible(true);
            } else if (aux.controle(this.codusu, PRODUTOS) == true) {
                tela.setVisible(true);
            }
            
            jlBotaoProtudos.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão produtos.png"));
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void clientes(){
        TelaClientes tela = null;
        try {
            tela = new TelaClientes(jlUsuarioConectado, this.codusu);
            AUXILIAR.AuxiliarControleAcesso aux = new AuxiliarControleAcesso();
            if (jlUsuarioConectado.getText().equals("ADM")) {
                tela.setVisible(true);
            } else if (aux.controle(this.codusu, CLIENTES) == true) {
                tela.setVisible(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void xml(){
        TelaLeituraXml tela = null;
        try {
            tela = new TelaLeituraXml(jlUsuarioConectado, this.codusu);
            AUXILIAR.AuxiliarControleAcesso aux = new AuxiliarControleAcesso();
            if (jlUsuarioConectado.getText().equals("ADM")) {
                tela.setVisible(true);
            } else if (aux.controle(this.codusu, XML) == true) {
                tela.setVisible(true);
            }

        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void movimento(){
        TelaMovimento tela = null;
        try {
            tela = new TelaMovimento(jlUsuarioConectado, this.codusu);

            AUXILIAR.AuxiliarControleAcesso aux = new AuxiliarControleAcesso();
            if (jlUsuarioConectado.getText().equals("ADM")) {
                tela.setVisible(true);
            } else if (aux.controle(this.codusu, MOVIMENTO) == true) {
                tela.setVisible(true);
            }

        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void contagens(){
        try {
            TelaContagens tela;
            tela = new TelaContagens(jlUsuarioConectado, this.codusu);

            AUXILIAR.AuxiliarControleAcesso aux = new AuxiliarControleAcesso();
            if (jlUsuarioConectado.getText().equals("ADM")) {
                tela.setVisible(true);
            } else if (aux.controle(this.codusu, CONTAGENS) == true) {
                tela.setVisible(true);
            }

        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void auditoria(){
        TelaLog tela;
        try {
            tela = new TelaLog();

            AUXILIAR.AuxiliarControleAcesso aux = new AuxiliarControleAcesso();
            if (jlUsuarioConectado.getText().equals("ADM")) {
                tela.setVisible(true);
                AUXILIAR.AuxiliarLog log = new AuxiliarLog();
                log.log(jlUsuarioConectado.getText(), "LOG", "CONSULTAR", Long.parseLong("555555"));
                tela.setVisible(true);
            } else if (aux.controle(this.codusu, AUDITORIA) == true) {
                tela.setVisible(true);
                AUXILIAR.AuxiliarLog log = new AuxiliarLog();
                log.log(jlUsuarioConectado.getText(), "LOG", "CONSULTAR", Long.parseLong("555555"));
                tela.setVisible(true);
            }

        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       auditoria();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        cfop();                
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        produtos();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        clientes();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        xml();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        movimento();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        contagens();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jlBotaoContagensMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoContagensMouseExited
        jlBotaoContagens.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão contagens.png"));
    }//GEN-LAST:event_jlBotaoContagensMouseExited

    private void jlBotaoContagensMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoContagensMouseEntered
        jlBotaoContagens.setIcon(new ImageIcon("C:\\Anve\\Icons\\botão contagens II.png"));
    }//GEN-LAST:event_jlBotaoContagensMouseEntered

    private void jlBotaoContagensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBotaoContagensMouseClicked
        contagens();

    }//GEN-LAST:event_jlBotaoContagensMouseClicked

    private void jmUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuarioActionPerformed
        usuarios();
    }//GEN-LAST:event_jmUsuarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        logout();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair do sistema?", null, 0);        
        if(resp == 0){
            dispose();
        }
        
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    int controleTeste = 0;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel jlBotaoCfop;
    private javax.swing.JLabel jlBotaoClientes;
    private javax.swing.JLabel jlBotaoContagens;
    private javax.swing.JLabel jlBotaoLog;
    private javax.swing.JLabel jlBotaoLogout;
    private javax.swing.JLabel jlBotaoMovimento;
    private javax.swing.JLabel jlBotaoProtudos;
    private javax.swing.JLabel jlBotaoUsuario;
    private javax.swing.JLabel jlBotaoXml;
    public javax.swing.JLabel jlUsuarioConectado;
    public javax.swing.JLabel jlUsuarioConectado1;
    public javax.swing.JLabel jlUsuarioConectado2;
    private javax.swing.JMenuItem jmUsuario;
    // End of variables declaration//GEN-END:variables
}
