/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import MODEL.ModelUsuarios;
import OperacaoBanco.OperacaoBancoUsuarios;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jxl.read.biff.BiffException;

/**
 *
 * @author André Felipe
 */
public class TelaLogin extends javax.swing.JFrame {

    final static int CODIGO_ADM = 0;
    
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfLogin = new javax.swing.JTextField();
        jtfSenha = new javax.swing.JPasswordField();
        jbCancelar = new javax.swing.JButton();
        jbEntrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login - Movimento XML - Versão 1.0");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuário");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jtfLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfLoginKeyReleased(evt);
            }
        });
        getContentPane().add(jtfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 160, -1));

        jtfSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfSenhaKeyReleased(evt);
            }
        });
        getContentPane().add(jtfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 160, -1));

        jbCancelar.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jbCancelar.setText("CANCELAR");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 90, 90, 30));

        jbEntrar.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jbEntrar.setText("ENTRAR");
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 90, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/TELA LOGIN.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 140));

        setSize(new java.awt.Dimension(593, 169));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfLoginKeyReleased
        jtfLogin.setText(jtfLogin.getText().toUpperCase());
    }//GEN-LAST:event_jtfLoginKeyReleased

    private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarActionPerformed
        try {
            
            ModelUsuarios usuarios = new ModelUsuarios();
            OperacaoBancoUsuarios obu = new OperacaoBancoUsuarios();

            Date data = new Date();
            String dia = new SimpleDateFormat("dd").format(data);
            String mes = new SimpleDateFormat("MM").format(data);

            int primeironumdia = Integer.parseInt(dia.substring(0, 1));
            int segundonumdia = Integer.parseInt(dia.substring(1, 2));
            int somadia = primeironumdia + segundonumdia;

            String senha = "ADM" + mes + Integer.toString(somadia);

            String login = jtfLogin.getText();
            String pass = jtfSenha.getText();
            System.out.println(login);
            System.out.println(pass);

            if (login.equals("ADM") && pass.equals(senha)) {
                usuarios.setLogin(login);
                TelaPrincipal tela = new TelaPrincipal(CODIGO_ADM);
                tela.setExtendedState(JFrame.MAXIMIZED_BOTH);
                tela.jlUsuarioConectado.setText(login);
                tela.setVisible(true);
                dispose();
            } else {

                String sql = "SELECT * FROM usuarios where login = " + login;
                obu.obterConexao();
                obu.executaSql("SELECT * FROM usuarios where login = '" + login + "'");
                obu.rs.first();
                String loginbanco = obu.rs.getString("login");
                String passbanco = obu.rs.getString("senha");
                int codigousuario = obu.rs.getInt("codusu");

                if (login.equals(loginbanco) && pass.equals(passbanco)) {
                    TelaPrincipal tela = new TelaPrincipal(codigousuario);
                    tela.jlUsuarioConectado.setText(login);
                    tela.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    tela.setVisible(true);
                    obu.fechaConexao();
                this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Login e Senha incorretos!");                    
                }
                
            }

        } catch (IOException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {

            //Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Login e Senha incorretos!");

        }


    }//GEN-LAST:event_jbEntrarActionPerformed

    private void jtfSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSenhaKeyReleased
        jtfSenha.setText(jtfSenha.getText().toUpperCase());
    }//GEN-LAST:event_jtfSenhaKeyReleased

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEntrar;
    private javax.swing.JTextField jtfLogin;
    private javax.swing.JPasswordField jtfSenha;
    // End of variables declaration//GEN-END:variables
}
