/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import AUXILIAR.AuxiliarConfirmacaoSaida;
import AUXILIAR.AuxiliarControleAcesso;
import AUXILIAR.AuxiliarLog;
import MODEL.ModelLog;
import MODEL.ModelTabela;
import MODEL.ModelUsuarios;
import OperacaoBanco.OperacaoBancoCfop;
import OperacaoBanco.OperacaoBancoLog;
import OperacaoBanco.OperacaoBancoProdutos;
import OperacaoBanco.OperacaoBancoUsuarios;
import java.io.IOException;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import jxl.read.biff.BiffException;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ANDREFELIPEFELICIOGO
 */
public class TelaUsuarios extends javax.swing.JFrame {

    final static int NOVO_USUARIO = 11;
    final static int EDITAR_USUARIO = 12;
    final static int EMITIR_RELATORIOS = 13;
    final static int CONTROLE_ACESSO = 14;

    JLabel recebedados;
    int codigousuario;
    JMenuItem menu;

    public TelaUsuarios() throws IOException, BiffException {
        initComponents();
        preencherTabela("SELECT * FROM usuarios");
    }

    public TelaUsuarios(JLabel transferedados, int codigousuario) throws IOException, BiffException {
        initComponents();
        recebedados = transferedados;
        this.codigousuario = codigousuario;

        preencherTabela("SELECT * FROM usuarios");
    }

    int flag = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfCodigo = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfLogin = new javax.swing.JTextField();
        jlNome1 = new javax.swing.JLabel();
        jlCod = new javax.swing.JLabel();
        jlLogin = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jtfSenha = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtUsuario = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbControleAcesso = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmNovo = new javax.swing.JMenuItem();
        jmSalvar = new javax.swing.JMenuItem();
        jmEditar = new javax.swing.JMenuItem();
        jmCancelar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuários - Movimento XML - Versão 1.0");
        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCodigo.setEnabled(false);
        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyReleased(evt);
            }
        });
        getContentPane().add(jtfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 65, -1));

        jtfNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfNome.setEnabled(false);
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNomeKeyReleased(evt);
            }
        });
        getContentPane().add(jtfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 390, -1));

        jtfLogin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfLogin.setEnabled(false);
        jtfLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfLoginKeyReleased(evt);
            }
        });
        getContentPane().add(jtfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 230, -1));

        jlNome1.setText("Nome");
        getContentPane().add(jlNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jlCod.setText("Codigo");
        getContentPane().add(jlCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jlLogin.setText("Login");
        getContentPane().add(jlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jlSenha.setText("Senha");
        getContentPane().add(jlSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        jtfSenha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfSenha.setEnabled(false);
        getContentPane().add(jtfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 220, -1));

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setOpaque(false);

        jtUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtUsuario.setGridColor(new java.awt.Color(204, 204, 204));
        jtUsuario.setInheritsPopupMenu(true);
        jtUsuario.setOpaque(false);
        jtUsuario.setRowHeight(20);
        jtUsuario.setSelectionBackground(new java.awt.Color(255, 102, 0));
        jtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUsuarioMouseClicked(evt);
            }
        });
        jtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtUsuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtUsuarioKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jtUsuario);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 460, 220));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Usuários");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 160, 90));

        jbCancelar.setText("CANCELAR");
        jbCancelar.setFocusable(false);
        jbCancelar.setOpaque(false);
        jbCancelar.setRequestFocusEnabled(false);
        jbCancelar.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jbCancelarHierarchyChanged(evt);
            }
        });
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 100, 40));

        jbEditar.setText("EDITAR");
        jbEditar.setEnabled(false);
        jbEditar.setFocusable(false);
        jbEditar.setOpaque(false);
        jbEditar.setRequestFocusEnabled(false);
        jbEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbEditarMouseClicked(evt);
            }
        });
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 90, 40));

        jbSalvar.setText("SALVAR");
        jbSalvar.setEnabled(false);
        jbSalvar.setFocusable(false);
        jbSalvar.setOpaque(false);
        jbSalvar.setRequestFocusEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 90, 40));

        jbControleAcesso.setText("Controle de acesso");
        jbControleAcesso.setFocusable(false);
        jbControleAcesso.setOpaque(false);
        jbControleAcesso.setRequestFocusEnabled(false);
        jbControleAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbControleAcessoActionPerformed(evt);
            }
        });
        getContentPane().add(jbControleAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 140, 30));

        jbNovo.setText("NOVO");
        jbNovo.setFocusable(false);
        jbNovo.setOpaque(false);
        jbNovo.setRequestFocusEnabled(false);
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jbNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 90, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/logomarca II.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 220, 90));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Ctrl+Z: Cancelar | Ctrl+R: Controle de Acesso");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 310, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Ctrl+N: Novo | Ctrl+S: Salvar | Ctrl+E: Editar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 320, -1));

        jlFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/TELA CLIENTE II.png"))); // NOI18N
        getContentPane().add(jlFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 530));

        jMenu2.setText("Opções");

        jmNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmNovo.setText("Novo");
        jmNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNovoActionPerformed(evt);
            }
        });
        jMenu2.add(jmNovo);

        jmSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmSalvar.setText("Salvar");
        jmSalvar.setEnabled(false);
        jmSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalvarActionPerformed(evt);
            }
        });
        jMenu2.add(jmSalvar);

        jmEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmEditar.setText("Editar");
        jmEditar.setEnabled(false);
        jmEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEditarActionPerformed(evt);
            }
        });
        jMenu2.add(jmEditar);

        jmCancelar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jmCancelar.setText("Cancelar");
        jmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCancelarActionPerformed(evt);
            }
        });
        jMenu2.add(jmCancelar);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Controle de Acesso");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Relatórios");

        jMenuItem1.setText("Lista de Usuários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(530, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void preencherTabela(String sql) throws IOException, BiffException {
        OperacaoBancoCfop obc = new OperacaoBancoCfop();
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"COD", "LOGIN", "NOME"};
        obc.obterConexao();
        obc.executaSql(sql);

        try {
            obc.rs.first();

            do {
                dados.add(new Object[]{
                    obc.rs.getInt("codusu"),
                    obc.rs.getString("login"),
                    obc.rs.getString("nome"),});
            } while (obc.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(rootPane, "Nenhum Usuário cadastrado");
        }

        ModelTabela modelo = new ModelTabela(dados, colunas);
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);

        jtUsuario.setModel((TableModel) modelo);
        jtUsuario.getColumnModel().getColumn(0).setPreferredWidth(90);
        jtUsuario.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        jtUsuario.getColumnModel().getColumn(0).setResizable(true);
        jtUsuario.getColumnModel().getColumn(1).setPreferredWidth(150);
        jtUsuario.getColumnModel().getColumn(1).setCellRenderer(esquerda);
        jtUsuario.getColumnModel().getColumn(1).setResizable(true);
        jtUsuario.getColumnModel().getColumn(2).setPreferredWidth(200);
        jtUsuario.getColumnModel().getColumn(2).setResizable(true);

        jtUsuario.getTableHeader().setReorderingAllowed(true);
        jtUsuario.setAutoResizeMode(jtUsuario.AUTO_RESIZE_OFF);
        jtUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        obc.fechaConexao();
    }


    private void jtfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyReleased
        jtfNome.setText(jtfNome.getText().toUpperCase());
    }//GEN-LAST:event_jtfNomeKeyReleased

    private void jtfLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfLoginKeyReleased
        jtfLogin.setText(jtfLogin.getText().toUpperCase());
    }//GEN-LAST:event_jtfLoginKeyReleased

    private void jtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuarioMouseClicked
        jtfCodigo.setText(jtUsuario.getValueAt(jtUsuario.getSelectedRow(), 0).toString());
        jtfNome.setText(jtUsuario.getValueAt(jtUsuario.getSelectedRow(), 2).toString());
        jtfLogin.setText(jtUsuario.getValueAt(jtUsuario.getSelectedRow(), 1).toString());

        jbEditar.setEnabled(true);
        jmEditar.setEnabled(true);
    }//GEN-LAST:event_jtUsuarioMouseClicked

    private void jtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtUsuarioKeyTyped

    }//GEN-LAST:event_jtUsuarioKeyTyped

    private void jtfCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoKeyReleased

    private void jtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtUsuarioKeyPressed

    }//GEN-LAST:event_jtUsuarioKeyPressed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jbCancelarHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarHierarchyChanged

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        cancelar();

    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        novo();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        editar();


    }//GEN-LAST:event_jbEditarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        AUXILIAR.AuxiliarControleAcesso aux = new AuxiliarControleAcesso();
        try {
            if (recebedados.getText().equals("ADM") || aux.controle(this.codigousuario, EMITIR_RELATORIOS) == true) {

                OperacaoBancoUsuarios ob = new OperacaoBancoUsuarios();
                ob.obterConexao();

                String src = "Jasper/relatorioListaUsuarios.jasper";
                JasperPrint jasperPrint = null;
                try {
                    jasperPrint = JasperFillManager.fillReport(src, null, ob.obterConexao());
                } catch (JRException ex) {
                    System.out.println("ERRO: " + ex.getMessage());
                }

                JasperViewer view = new JasperViewer(jasperPrint, false);
                view.setVisible(true);
                ob.fechaConexao();

            }
        } catch (IOException ex) {
            Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbControleAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbControleAcessoActionPerformed
        controleacesso();
    }//GEN-LAST:event_jbControleAcessoActionPerformed

    private void jmNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNovoActionPerformed
        novo();
    }//GEN-LAST:event_jmNovoActionPerformed

    private void jmSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_jmSalvarActionPerformed

    private void jmEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEditarActionPerformed
        editar();
    }//GEN-LAST:event_jmEditarActionPerformed

    private void jmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_jmCancelarActionPerformed

    private void jtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtUsuarioKeyReleased
        jtfCodigo.setText(jtUsuario.getValueAt(jtUsuario.getSelectedRow(), 0).toString());
        jtfNome.setText(jtUsuario.getValueAt(jtUsuario.getSelectedRow(), 2).toString());
        jtfLogin.setText(jtUsuario.getValueAt(jtUsuario.getSelectedRow(), 1).toString());

        jbEditar.setEnabled(true);
        jmEditar.setEnabled(true);
    }//GEN-LAST:event_jtUsuarioKeyReleased

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        controleacesso();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEditarMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (flag == 0) {
            this.dispose();
        } else if (flag == 1) {

            int resp = JOptionPane.showConfirmDialog(null, "Os dados preenchidos serão perdidos, deseja sair?", null, 0);
            if (resp == 0) {
                this.dispose();
            }
        } else if (flag == 2) {
            int resp = JOptionPane.showConfirmDialog(null, "A alteração do cadastro não foi salva, deseja sair??", null, 0);
            if (resp == 0) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public void novo() {
        AUXILIAR.AuxiliarControleAcesso aux = new AuxiliarControleAcesso();
        try {
            if (recebedados.getText().equals("ADM") || aux.controle(this.codigousuario, NOVO_USUARIO) == true) {
                flag = 1;
                jtfLogin.setEnabled(true);
                jtfNome.setEnabled(true);
                jtfSenha.setEnabled(true);
                jbSalvar.setEnabled(true);
                jmSalvar.setEnabled(true);
                jtfLogin.setText("");
                jtfNome.setText("");
                jtfSenha.setText("");
                jtfNome.requestFocus();
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void salvar() {
        if (flag == 1) {
            int i = 0;

            while (i == 0) {
                if (jtfNome.getText().equals("") || jtfLogin.getText().equals("") || jtfSenha.getText().equals("")) {
                    i = 0;
                    jtfNome.requestFocus();
                    break;
                } else {
                    i = 1;

                    try {
                        OperacaoBanco.OperacaoBancoUsuarios obu = new OperacaoBancoUsuarios();
                        MODEL.ModelUsuarios usuario = new ModelUsuarios();

                        obu.obterConexao();
                        usuario.setLogin(jtfLogin.getText().toUpperCase());
                        usuario.setNome(jtfNome.getText().toUpperCase());
                        usuario.setSenha(jtfSenha.getText().toUpperCase());

                        obu.incluirUsuarios(usuario);
                        obu.fechaConexao();

                        jbNovo.setEnabled(true);
                        jbSalvar.setEnabled(false);
                        jmSalvar.setEnabled(false);
                        jbEditar.setEnabled(false);
                        jmEditar.setEnabled(false);
                        jtfLogin.setText("");
                        jtfNome.setText("");
                        jtfSenha.setText("");
                        jtfCodigo.setText("");
                        jtfLogin.setEnabled(false);
                        jtfNome.setEnabled(false);
                        jtfSenha.setEnabled(false);

                        preencherTabela("SELECT * FROM usuarios");

                    } catch (IOException ex) {
                        Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BiffException ex) {
                        Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (Exception ex) {
                        Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

            try {
                AUXILIAR.AuxiliarLog aux = new AuxiliarLog();
                jtUsuario.changeSelection(jtUsuario.getRowCount() - 1, jtUsuario.getRowCount(), false, false);
                aux.log(recebedados.getText(), "USUARIOS", "INCLUIR", Long.parseLong(jtUsuario.getValueAt(jtUsuario.getSelectedRow(), 0).toString()));
            } catch (IOException ex) {
                Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BiffException ex) {
                Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {

            int i = 0;

            while (i == 0) {
                if (jtfNome.getText().equals("") || jtfLogin.getText().equals("") || jtfSenha.getText().equals("")) {
                    i = 0;
                    jtfNome.requestFocus();
                    break;
                } else {
                    i = 1;

                    try {
                        OperacaoBanco.OperacaoBancoUsuarios obu = new OperacaoBancoUsuarios();
                        MODEL.ModelUsuarios usuario = new ModelUsuarios();

                        obu.obterConexao();
                        usuario.setCodusu(Integer.parseInt(jtfCodigo.getText()));
                        usuario.setLogin(jtfLogin.getText().toUpperCase());
                        usuario.setNome(jtfNome.getText().toUpperCase());
                        usuario.setSenha(jtfSenha.getText().toUpperCase());

                        obu.alterarUsuarios(usuario);
                        obu.fechaConexao();

                        preencherTabela("SELECT * FROM usuarios");

                    } catch (IOException ex) {
                        Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BiffException ex) {
                        Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (Exception ex) {
                        Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            AUXILIAR.AuxiliarLog aux = new AuxiliarLog();
            try {
                aux.log(recebedados.getText(), "USUARIOS", "ALTERAR", Long.parseLong(jtfCodigo.getText().toString()));
            } catch (IOException ex) {
                Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BiffException ex) {
                Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);
        jmSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jmEditar.setEnabled(false);
        jtfLogin.setText("");
        jtfNome.setText("");
        jtfSenha.setText("");
        jtfCodigo.setText("");
        jtfLogin.setEnabled(false);
        jtfNome.setEnabled(false);
        jtfSenha.setEnabled(false);
        flag = 0;
    }

    public void editar() {
        AUXILIAR.AuxiliarControleAcesso aux = new AuxiliarControleAcesso();
        try {
            if (recebedados.getText().equals("ADM") || aux.controle(this.codigousuario, EDITAR_USUARIO) == true) {
                flag = 2;
                jtfSenha.setEnabled(true);
                jbSalvar.setEnabled(true);
                jmSalvar.setEnabled(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void cancelar() {
        jtfCodigo.setText("");
        jtfLogin.setText("");
        jtfLogin.setEnabled(false);
        jtfNome.setText("");
        jtfNome.setEnabled(false);
        jtfSenha.setText("");
        jtfSenha.setEnabled(false);

        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);
        jmSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jmEditar.setEnabled(false);
        jtUsuario.clearSelection();
        flag = 0;
    }

    public void controleacesso() {
        AUXILIAR.AuxiliarControleAcesso aux = new AuxiliarControleAcesso();
        try {
            if (recebedados.getText().equals("ADM") || aux.controle(this.codigousuario, CONTROLE_ACESSO) == true) {
                TelaControleAcesso tela = new TelaControleAcesso(jtfNome.getText(), Integer.parseInt(jtfCodigo.getText().toString()));
                tela.setVisible(true);

                AUXILIAR.AuxiliarLog log = new AuxiliarLog();
                jtUsuario.changeSelection(jtUsuario.getRowCount() - 1, jtUsuario.getRowCount(), false, false);
                log.log(recebedados.getText(), "USUARIOS", "CONTROLE DE ACESSO", Long.parseLong(jtfCodigo.getText().toString()));

            }
        } catch (IOException ex) {
            Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Selecione um usuário!!!");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Selecione um usuário!!!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaUsuarios().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (BiffException ex) {
                    Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbControleAcesso;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlCod;
    private javax.swing.JLabel jlFundo;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlNome1;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JMenuItem jmCancelar;
    private javax.swing.JMenuItem jmEditar;
    private javax.swing.JMenuItem jmNovo;
    private javax.swing.JMenuItem jmSalvar;
    private javax.swing.JTable jtUsuario;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfLogin;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JPasswordField jtfSenha;
    // End of variables declaration//GEN-END:variables
}
